#:schema node_modules/wrangler/config-schema.json
name = "sub-converter"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "c8a0c1812bb24790b97edfb9502a9731" }
]
